### ISSUE TITLE
Add furigana on subtitles

### ISSUE THREAD

**Issue by OltiP2** [killergerbah/asbplayer#126]
having an option to turn furigana on/off for subtitles

**Comment by killergerbah** [comment]
Processing language isn't asbplayer's intended use, and there are a lot of other programs that are better at doing this. I would also argue that asbplayer is good at doing what it does (making flash cards) because it leaves those problems to other tools such as Yomi-chan.

I googled "adding furigana to Anki cards" and found that BrittVsJapan wrote a blog post on how to do what you want just using Anki plugins - maybe it could help you: https://www.britvsjapan.com/adding-furigana-to-japanese-in-anki/

**Comment by OltiP2** [comment]
no i meant furigana on the subtitles not on the anki card like when you watching and show and you can enable the option to see furigana when your are watching the show on the subtitles
