### ISSUE TITLE
"You need to enable JavaScript to run this app."

### ISSUE THREAD

**Issue by AsuraAce** [killergerbah/asbplayer#128]
Sometimes the above mentioned string will be added to my Anki cards in the Sentence & Sentence Furigana fields (with Yomichan).
It only happens when the target word is at the start of the sentence. Tested it MPV-Player as well, had no issues there.

- Win11
- Microsoft Edge browser

![image](https://user-images.githubusercontent.com/13394741/158442420-4c2e49ef-06fa-42fb-a7a6-8e3686adb72f.png)

**Comment by OltiP2** [comment]
What add-on do you use

**Comment by killergerbah** [comment]
@AsuraAce are you seeing this for local files or streaming videos or both?

**Comment by AsuraAce** [comment]
- local files only.
- sentence created with yomichan not asbplayer.
- only happens with words at the beginning of a sentence.

it worked perfectly fine in the beginning. idk when it broke. if it is related to asbplayer it might have been the 17.0 update. but it maybe browser related, not sure.

**Comment by killergerbah** [comment]
@AsuraAce Looked at this for a bit - it seems more likely to be something caused by a Yomi-chan upgrade. I haven't updated anything to do with the way the app renders in a while.

For context, "You need to enable JavaScript to run this app" is actual text that's in the site's DOM. It's not rendered, though, because your browser is actually running JavaScript. Yomi-chan seems to be picking it up as part of the sentence, though, for some reason. Out of curiosity, when you create the card with Yomi-chan, what are you scanning? The subtitle player, the Anki dialog, or the subtitle that's rendered in the video player?
 
Also, have you tried tweaking the sentence scanning options on Yomi-chan?

**Comment by AsuraAce** [comment]
Have been scanning the subtitle that is rendered in asbplayer, the one below/within the video. 

Played around with Yomichan as well but couldn't figure something out and was to lazy to try and setup everything again with a different browser.

I use asbplayer to export to Anki now. The reason I used Yomichan before aren't important/relevant anymore. Thanks for taking your time.
