### ISSUE TITLE
subtitles are really long line watch's make it really hard to read while watching movies

### ISSUE THREAD

**Issue by nzarbayezid** [killergerbah/asbplayer#149]
there is a bit of a problem with how the subtitle appearance works with the extension. I'm gonna try to explain the problem in this video

https://user-images.githubusercontent.com/101425664/174746971-38cc39ae-b069-4e66-8b4d-a38e7fa5425c.mp4

**Comment by killergerbah** [comment]
Thanks for pointing out these issues. It would be easy to add an option that takes newlines into account when rendering subtitles in video.

Also, it should be also simple to take into account italics etc.

**Comment by nzarbayezid** [comment]
What about those symbols?

![image](https://user-images.githubusercontent.com/101425664/175208637-9a3b496f-9ea1-4a1d-8997-ee30011c831c.png)

and hopefully you can bring the new update as soon as posable because we mentioned a lot of bugs that can improve the extension, is is is it possible for this week? or you are busy

**Comment by killergerbah** [comment]
Yeah we should be able to take care of those tags.
I'm currently travelling but when I get back home I can see about doing a small release with quick fixes for some of the issues you've pointed out.

**Comment by killergerbah** [comment]
I was able to fix the issue with newlines.

As for the `<i>`, etc tags, I've opted to simply remove them. 

The reason is a bit complicated but here it is: SRT supports a limited set of tags for formatting text but it would be difficult to support all of them. Furthermore, currently asbplayer has no knowledge of the file type that a subtitle originally came from so it would be potentially dangerous to simply try to render the subtitle as HTML. Fully supporting subtitle formatting in a file-type-agnostic way would be a very high effort task for arguably low value given that asbplayer is intended for language learning.

**Comment by killergerbah** [comment]
a18313fcef04b9055c7951657fb2ceaf24243cb3

**Comment by killergerbah** [comment]
The website is updated with these fixes.
The next extension release will include the line-breaks change.

**Comment by nzarbayezid** [comment]
dose all the bug fixes apply to the Netflix site or do we have to wait for the new release of the extension?

https://user-images.githubusercontent.com/101425664/175762241-61be54be-6056-477e-a4d2-b2d54dc06d52.mp4

**Comment by killergerbah** [comment]
Needs an extension release. Actually I'll just post a build here for you @nzarbayezid so you don't need to wait for an "official" release.

[asbplayer-extension-0.18.3-snapshot.zip](https://github.com/killergerbah/asbplayer/files/8984954/asbplayer-extension-0.18.3-snapshot.zip)

**Comment by nzarbayezid** [comment]
thanks a lot dude
