### ISSUE TITLE
Option to remove line breaks from subtitles

### ISSUE THREAD

**Issue by killergerbah** [killergerbah/asbplayer#195]
Makes it easier for Yomichan to detect the whole subtitle as a sentence.

From Discord:
UMNV_Leo — 今日 13:20
@killergerbah is it possible for asbplayer ignore or remove the <br> from subtitles to use it with yomichan? maybe an option we can toggle? what i noticed is if a subtitle has 2 or more lines yomichan only gets the one you selected the word from. What i've been doing to avoid that is to edit the subtitles on a program to remove the <br> and changing "Sentence termination" to "newlines only" on yomichan. here's a video with an example:

**Comment by Aquafina-water-bottle** [comment]
Just wanted to put this somewhere: I believe the underlying problem here is that asbplayer doesn't preserve the bolded text from Yomichan. I've been looking at how mpvacious does it, and it seems to do it a bit smartly by grabbing the text within Anki first, and then using this function to preserve the html marked text while still updating the sentence: https://github.com/Ajatt-Tools/mpvacious/blob/b06e83dd12a1867228b6c0fbf535c351eff9650e/subs2srs.lua#L313
It's not completely perfect, i.e. if there's other html tags around the sentence for some reason, then it won't be preserved. However, I don't think people usually add html tags around the prefix/suffix anyways. If you're looking into this issue, maybe try doing this as a togglable option as well?

**Comment by killergerbah** [comment]
This is a clever solution; thanks for pointing it out!

**Comment by killergerbah** [comment]
Subtitle regex filter can achieve the same result.
