### ISSUE TITLE
Doesn't detect U-Next JP at all

### ISSUE THREAD

**Issue by gitiko** [killergerbah/asbplayer#21]
Hi, I have purchased a U-Next streaming account for viewing anime, but for some reason, despite doing everything properly, Asbplayer doesn't detect any U-Next streaming video. I've made sure none of the videos are in incognito, made sure the video is playing so Asbplayer can detect it, and I've turned off Brave adblocker in case that was the issue. Is this an issue which is personal, or does the owner need to fix it? Thanks @killergerbah

**Comment by killergerbah** [comment]
The extension attempts to make as few assumptions as possible about video players on other sites, but it looks like it failed in the case of U-Next. I'll take a look at a fix.

**Comment by killergerbah** [comment]
Hey @gitiko I wasn't able to reproduce the issue. Here is a recording of what I did to sync asbplayer with U-Next: [https://youtu.be/5nqoSamX7QQ](url)

Are you experiencing the issue with other sites as well? Another thing that that might break the extension is reloading it in the extension manager and then forgetting to reload both asbplayer and the streaming video site.

There is a bug with U-Next where subtitles don't appear in fullscreen mode. A workaround is to use F11 instead of using U-Next's fullscreen button. However this doesn't appear to be the bug you're referring to.

It would be helpful if you could provide some more info: 
1. Console logs when playing the video (Chrome menu -> Other Tools -> Developer Tools -> Console)
2. Extension logs when playing the video (Extension manager -> asbplayer -> background page)

If either of those logs are empty that's helpful information too.

**Comment by killergerbah** [comment]
Also @gitiko just want to make sure - did you install the extension? asbplayer can't detect videos in other tabs without the [extension](https://github.com/killergerbah/asbplayer/releases/latest)

**Comment by gitiko** [comment]
@killergerbah This was the issue.

> "Break[ing] the extension [when] it is reloading it in the extension manager and then forgetting to reload both asbplayer and the streaming video site.

 I just tried it again, and it works just fine now. Thanks for the help. I did install the extension, yes.
