### ISSUE TITLE
When exporting a new card to Anki via Ctrl+Shift+X hotkey, "cannot create note because it is empty" error pops up

### ISSUE THREAD

**Issue by Flashbang42** [killergerbah/asbplayer#220]
Saw a comment under this video (https://www.youtube.com/watch?v=Mv7fEVb6PHo&t=44s&ab_channel=R-JLim) detailing the same problem I currently have, to which the answer is that the front of the field of the card is blank; how do I make the front field of my card not blank? My apologies for any repetition or if this is a common mishap.

**Comment by killergerbah** [comment]
@Flashbang42 
- Look at your note type in Anki. Note down the field that's on the front of the card.
- Look at your asbplayer settings https://killergerbah.github.io/asbplayer/?view=settings . Make sure that that field you just noted down is selected for one of "Sentence" or "Word" (depends on whether you're making sentence or vocab cards)
- Click OK to save settings
- When you export a card make sure both sentence and word are filled out in the Anki dialog.

**Comment by Flashbang42** [comment]
> @Flashbang42
> 
> * Look at your note type in Anki. Note down the field that's on the front of the card.
> * Look at your asbplayer settings https://killergerbah.github.io/asbplayer/?view=settings . Make sure that that field you just noted down is selected for one of "Sentence" or "Word" (depends on whether you're making sentence or vocab cards)
> * Click OK to save settings
> * When you export a card make sure both sentence and word are filled out in the Anki dialog.

My apologies for my delayed response. Looking at my note type, how do I know which field is on the front of my card?  Again, sorry for the confusion, I'll send screenshots to try and explain my problem/lack of understanding :) I'll also add that I'm trying to mine sentence cards. I've been attempting to follow this guide (https://aquafina-water-bottle.github.io/jp-mining-note/setupeverythingelse/) but have somehow fallen short 😅

![ss1](https://user-images.githubusercontent.com/129286593/228730875-407c3fbf-4266-4238-ab2f-da79396281d7.PNG)
![ss2](https://user-images.githubusercontent.com/129286593/228730994-41dc90c9-1af6-4fa8-a702-863baefe5f4a.PNG)
![ss3](https://user-images.githubusercontent.com/129286593/228732318-3a53b57f-6c70-4ac2-ab81-c79fde26dec7.PNG)

Thanks for your time in advance :)

**Comment by killergerbah** [comment]
Resolved on discord

**Comment by jorgeazevedo** [comment]
For future travellers:

The error "cannot create note because it is empty" is thrown when attempting to create a  "jp-mining-note" card directly from asbplayer without setting the note's "key" field, which is a necessary field for this card type. You can see this play out by using ctrl-shit-x and clicking "open in anki" instead of "export".

While there is a workaround to make the card creation succeed (you can set "key" as the "word field" in asbplayer's settings screen, for example), the resulting card will not be usable due to other important fields missing.

The real problem here is attempting to create a "jp-mining-note" card directly from asbplayer. The actual intend workflow is as follows:
- Bring up the yomichan definition of a word in the subtitles using shift+mouse hover
- Click the green "add" icon on the top right to create the "jp-mining-note" card
- Press ctrl-shit-u to trigger asbplayer to append a screenshot and an audio recording to the card created by yomichan (alternative: ctrl-shift-x to bring up the dialog to make minor edits, and then click "update last card")

You can see this workflow in this [youtube video at the 4:20 mark](https://youtu.be/B60cj69MSmA?t=260).
