### ISSUE TITLE
Better compatibility with Kiwi browser (mobile)

### ISSUE THREAD

**Issue by killergerbah** [killergerbah/asbplayer#249]
It seems some people are using old versions of asbplayer just to add subtitles onto videos.
If we ignore mining features, it may be possible to make newer versions of the extension work as well, and better than the older versions. One idea is to use the upcoming side panel API.

Edit:
Some more goals for this issue:
- Implement mobile-only gestures to trigger the subtitle track selector and the Anki dialog
- P2: Mobile-only settings to control what the mining gesture would do, could be open Anki dialog or update last card
- Fix popup rendering issues on mobile
- Disable the Side Panel button in the popup. Possibly replace it with something else, maybe "Open subtitle track selector in last selected tab"
- Implement convenience gestures for seeking through subtitles, adjusting offset

**Comment by Xelieu** [comment]
Hello, since Kiwi Browser already supports Yomichan, it would be a better idea to first support mobile properly on asbplayer such as:

- **Proper Video Player View**, as right now the alignment of the video is messed up due to the subtitle window
- Upon zooming out of the Video Player, the ← key to check the subtitles **must be properly aligned** without needing to Landscape
- Give the basic settings to edit the **size and positions of the subtitle**
- Give a way to configure the subtitle offset on touchscreen

This way, we can already mine using Kiwi Browser and Yomichan without the built-in support yet for auto ss and audio which is the hard part, prioritizing this first is the easiest while already a big step-up in the game

**Comment by killergerbah** [comment]
> Hello, since Kiwi Browser already supports Yomichan, it would be a better idea to first support mobile properly on asbplayer such as:
> 
> * **Proper Video Player View**, as right now the alignment of the video is messed up due to the subtitle window
> * Upon zooming out of the Video Player, the ← button to check the subtitles **must be properly aligned** without needing to Landscape
> * Give the basic settings to edit the **size and positions of the subtitle**
> * Give a way to configure the **subtitle offset** on touchscreen
> 
> This way, we can already mine using Kiwi Browser and Yomichan without the built-in support yet for auto ss and audio which is the hard part, prioritizing this first is the easiest while already a big step-up in the game
> 
> Mining already works on Mobile, the combo is Kiwi Browser + Yomichan + [AnkiConnect Android](https://github.com/KamWithK/AnkiconnectAndroid/releases/latest) + AnkiDroid For more info: [Android Mining](https://xelieu.github.io/jp-lazy-guide/setupLnOnAndroid/)

These issues are addressed, except possibly for the subtitle offset for the video player. Technically it is possible to type in an offset through the controls but there is probably a better solution like what is implemented now in the streaming video controls overlay.

**Comment by killergerbah** [comment]
I've implemented an overlay that makes it possible to mine streaming video from Kiwi Browser. There is a problem where screenshots do not work on Kiwi Browser for which I have not found a workaround, but amazingly audio recording works.
