### ISSUE TITLE
asbplayer is not showing the subtitle correctly

### ISSUE THREAD

**Issue by ostovane** [killergerbah/asbplayer#282]
I checked the subtitle with other players and it works.
but it doesn't work on asb player
![Screenshot (128)](https://github.com/killergerbah/asbplayer/assets/139720878/88de4535-e537-4293-ad71-71f8f2088707)

**Comment by killergerbah** [comment]
@ostovane Can you upload the subtitle file here?

**Comment by ostovane** [comment]
[Doom.Patrol.S01E01.GERMAN.720P.WEB.H264.INTERNAL-WAYNE.mkv.zip](https://github.com/killergerbah/asbplayer/files/12333713/Doom.Patrol.S01E01.GERMAN.720P.WEB.H264.INTERNAL-WAYNE.mkv.zip)
@killergerbah

**Comment by ostovane** [comment]
This problem can be fixed by opening the subtitle in notepad and then save it as utf8.

**Comment by killergerbah** [comment]
This looks like an issue with character encoding.
I can think of two possible solutions:
1. Provide way for user to declare the file encoding.
2. Have asbplayer try to detect the file encoding.

I do not think 1) is viable because it assumes technical competence and time that most users do not have.
I do not think 2) is viable because encoding detection is probabilistic and opens up some surface area for bugs.
Instead, I think we are better off declaring asbplayer as supporting Unicode-encoded files only.
