### ISSUE TITLE
disable the recording tab from appearing

### ISSUE THREAD

**Issue by kurakurakantor** [killergerbah/asbplayer#358]
i'm not using the anki recording thingy, disabled the recording option, but the pinned tab used for recording keeps appearing so i would have to close it manually myself

it's not exactly a functional request, but it would be nice if the tab wouldn't be summoned if you disable it :D

i'm not sure how hard that would be to implement though, maybe there's a reason why it's still there even if i'm not using the feature

here's the pinned tab thingy i'm talking about
![image](https://github.com/killergerbah/asbplayer/assets/101485444/b1ea1a1d-0e65-4c03-8219-f919da750e00)

this is unrelated but thank you so much for creating this! seeking through subtitles is so awesome i wish it's a feature in all of media players...

**Comment by killergerbah** [comment]
@kurakurakantor unfortunately the pinned tab is not only used for audio recording but some other background tasks like saving mining history from the asbplayer website. In the future it might be used for some other tasks since it is quite useful to have. So it's not super easy to just disable but I will think more about it.

**Comment by killergerbah** [comment]
I discovered that IndexedDB can be used to from service workers to store the mining history, so with the next version of the extension the pinned tab will not show if audio recording is disabled.
