### ISSUE TITLE
Automatic subtitle downloader 

### ISSUE THREAD

**Issue by ONEsuzuki** [killergerbah/asbplayer#359]
**Is your feature request related to a problem? Please describe.**
I always download all my subs from everything I watch from Netflix that has them because if it moves to another streaming service like amazon or Disney+, I can always just hook the subtitles right back up to the video since these other platforms aren't as good at providing foreign subtitles, which is why I keep my own collection of subtitles. 

**Describe the solution you'd like**
I've been using Subadub to download subtitles as srt but I just noticed that you can download the subtitles with the asbplayer, wondering if you could set it up to rip out all the subtitles of the seasons automatically or even just the current season I'm on. 

**Describe alternatives you've considered**
I don't know of any alternatives.

**Additional context**
I remember you saying about the "export all subtitle audio to mp3" feature, not being able to see future episodes or something but you might be able to do it, but I'm not sure on logistics just a thought.

**Comment by killergerbah** [comment]
@ONEsuzuki I think it's unlikely that asbplayer would get a feature like this anytime soon since it would require a larger integration with Netflix beyond just knowing how to retrieve subtitles for the thing you are watching. You could do this somewhat efficiently however by enabling the "auto-load detected subtitles" setting, and clicking through every episode while keeping the side panel open. Once the subtitles for the current episode load into the side panel you can download them immediately.

**Comment by ONEsuzuki** [comment]
That's for the insight I didn't really think about speeding up the process by just using the side bar, thanks and have a nice day.
