### ISSUE TITLE
One click mining not working with youtube

### ISSUE THREAD

**Issue by mariano54** [killergerbah/asbplayer#387]
The one click mining feature does not work on youtube. When adding the note through yomitan, I get the error:

Enable audio recording: Click on the asbplayer action button in the top-right of the browser window to enable audio recording for this tab.

This might be user error. I am able to get recording working if I mine the old way, but not with the one click mining and the go ankiconnect proxy.

**Comment by mariano54** [comment]
I'm also happy to help fix this if I can get some guidance on which files in the codebase I need to look at.

**Comment by killergerbah** [comment]
Hi, the behavior you're describing is intended because audio-recording permissions need to be acquired manually when not using keyboard shortcuts or the context menu items for mining. 

However, if mining still does not work even after clicking the asbplayer icon in the top-right of the browser window then there is a bug. I have not been able to reproduce this behavior.

**Comment by killergerbah** [comment]
This is a demo of what is expected, including clicking on asbplayer's action icon to enable recording:

https://github.com/killergerbah/asbplayer/assets/2254858/ec89fae9-7909-4c2f-ac09-c020fa50bca7
