### ISSUE TITLE
Error: 'utf-8' codec can't encode character '\ud835' in position 22: surrogates not allowed

### ISSUE THREAD

**Issue by tanhoaian01** [killergerbah/asbplayer#455]
Hello, I'm having a problem adding card to Anki. Whenever I hit Ctrl + Shift + X to mine a sentence and update last card, it shows the error as below picture. 

![2024_06_29_09-37__psT](https://github.com/killergerbah/asbplayer/assets/133650669/027353bb-e4d6-45f5-a14e-df8570dec676)

Is it something to do with [my video and subtitle files](https://drive.google.com/drive/folders/1mWMLx6VTQAk7OeYBkWXu4GyaZVRwftwB?usp=sharing)? Both of them are downloaded from youtube with yt-dlp. Appreciate your reply, Thanks in advanced!

**Comment by killergerbah** [comment]
This appears to a bug related to how asbplayer is deriving the audio file name for the card. For this particular video I would suggest downloading the subtitle file, renaming it so that "Thunderstorm - 8 CC SUBS" uses plain letters (and not special unicode ones), and loading it up again. This way the derived audio file name won't be broken.

**Comment by killergerbah** [comment]
Fix is deployed for the website.
Next extension release will also have the fix.

**Comment by tanhoaian01** [comment]
Thank you. Just a heads up, it's because of the emoji in the file title. I removed the emoji and was able to mine again
