### ISSUE TITLE
How do I implement the fix for Trusted HTML assignment subtitle bug on YouTube?

### ISSUE THREAD

**Issue by Loongoon** [killergerbah/asbplayer#490]
The post I'm referring to is this one:

https://github.com/killergerbah/asbplayer/issues/482

I see that a way to solve this bug has been found, but I'm not the most tech savvy person and so I'm confused on how to implement this fix. How do I access the code for the asbplayer  web browser version (chromium) to change the line of code?

**Comment by Julian-Ludwig** [comment]
You yourself dont have to implement anything. The fix was already released in version 1.4.0. But this release version is not yet visible on the chrome extention store. So you have to manually add it. So download the prerelease version here: https://github.com/killergerbah/asbplayer/releases/tag/v1.4.0 
(asbplayer-extension-1.4.0-chromium.zip)

And follow the steps written under **Installation on Chromium-based browsers**

<img width="1042" alt="image" src="https://github.com/user-attachments/assets/0484a426-c9dc-4f7a-8017-2b71a1ce8b03">

Unfortunally i still get an error,  but a different one:

<img width="449" alt="image" src="https://github.com/user-attachments/assets/f0d552bc-15ac-4b10-8d41-8740fded5590">

**Comment by Loongoon** [comment]
Yeah, after following those steps I'm also getting the same new error code.
![image](https://github.com/user-attachments/assets/e7c72f15-bdde-4ef5-bec2-3e19bb9679ec)

**Comment by Daii1414** [comment]
As I wrote in my report, this problem is repeated with the new version of this plugin that I installed directly from GitHub. Yesterday, my friends and I tried to solve the problem by installing the new version of the plugin, but the error just changed a little, but did not disappear

**Comment by Varangian6** [comment]
The same thing, it doesn't work at all, whether it's the new version or the precious one. Will it be even solved?

**Comment by Loongoon** [comment]
Yup the 1.4.1 version has solved the issue for me. Thanks a ton!
