### ISSUE TITLE
Amazon Prime?

### ISSUE THREAD

**Issue by Jakim287** [killergerbah/asbplayer#50]
Hello

Would it be possible to make Amazon Prime work with asbplayer? Not sure if this is even possible, but since I tested it with Netflix and it worked without any problems, I wondered if it would be possible to make it work with Amazon Prime.

It does detect the video playing but is unable to sync the subtitles.

Kind regards

**Comment by killergerbah** [comment]
Interesting, will take a look.

**Comment by killergerbah** [comment]
There appear to be a couple issues with Amazon Prime:

1. The player is an overlay on top of the site, so there are actually two video elements present on the page. At the moment, asbplayer (stupidly) assumes the first video element on the page is the one that we want to sync. It shouldn't be difficult to fix this.
2. When copying a subtitle, the Amazon player seems to be doing something special that presents seeking to the beginning of the current subtitle from working. Hopefully it's not too hard to find a workaround.

I'll see if I can fix these issues over the next few days.

**Comment by Jakim287** [comment]
Ok, keep me updated!

Thanks for your effort!

**Comment by killergerbah** [comment]
I was able to solve the above issues, although the workaround for 2) wasn't pretty (basically, play the video until it actually starts playing). The Amazon Prime player seems to have a lot of built in hooks that mess with the state of the video element when buffering, so starting at a paused state, trying to seek and then play the video is a bit clunky, although for mining subtitles it doesn't seem to present huge issues except for a tiny delay in the audio recording.

There is a third issue which I didn't mention above, which is that if the video resolution is lower than that of your screen, the image that's produced will look over-cropped. This is because the way we fetch the dimensions of the video doesn't take into account the transformation that Amazon's player does to expand the video to fit the screen. To work around this, I'll add an option to disable cropping of the video image. Since Amazon's player takes up the whole screen by default this should be sufficient for mining subtitles with clean screenshots.

**Comment by Jakim287** [comment]
Thanks for the update. Since you've mentioned that the Amazon Prime Player had a lot of built in hooks that messed with the video. (Not sure what that means :$). I tried to see if i could play the video in another video player. This wasn't possible but I stumbled upon Amazon Watch Party. If you click on it, it opens the video in a sort of different player and for some reason it works. I'm able to sync the subtitles with the video with no issues. 

No idea why it works but it does. Maybe something is different with that specific player?

**Comment by killergerbah** [comment]
Probably what's happening with watch party is that it's opening a video player either in another page where that player is the only video element on the page, or it's opening a video element that becomes the first in the list of video elements on that page, and so asbplayer picks it as the "syncable" video element on that page. This has to do with problem 1) that I mentioned above where asbplayer only picks the first video element on a page as the syncable one. This will be fixed when I release the next version of the extension.

The other issue you are mentioning where the video blows up when you press Cmd+Shift+Z has to do with the "hooks" I mentioned in issue 2). When the extension tries to seek back to the beginning of the current subtitle and play the video, the Amazon player simultaneously tries to pause the video, causing an exception in the mining code and some state to not be cleaned up e.g. the controls might be hidden forever. This is also fixed by my current set of changes.

So my guess is that watch party is basically using the same player, but it's fixing the syncing issue in 1) for the reasons I mentioned above, but isn't fixing issue 2) because it's still the same Amazon Prime video player.

Either way, both of these things should be fixed with the next release hopefully today or tomorrow.

**Comment by killergerbah** [comment]
I've finished the changes for this. I'll test a bit more and release the extension tomorrow morning.

**Comment by killergerbah** [comment]
The fixes are in the latest version of the extension: https://github.com/killergerbah/asbplayer/releases/tag/v0.9.0
@Jakim287 Let me know if you have any more issues.
