### ISSUE TITLE
Make extension compatible with Firefox

### ISSUE THREAD

**Issue by killergerbah** [killergerbah/asbplayer#62]

**Comment by killergerbah** [comment]
tabCapture API isn't implemented in Firefox, so this ticket may not be worth it.

**Comment by killergerbah** [comment]
Not implementing, flashcards without audio is a deal breaker

**Comment by mapma1** [comment]
could you still do this? even if flashcards without audio aren't something that'll work, it's nice to use this extension to add japanese subtitles to raw streams of anime

**Comment by killergerbah** [comment]
@mapma1 Sure I'll re-open this

**Comment by pedipanol** [comment]
bumping this, would be nice if asb was on firefox even if feature-limited
there are alternatives such as Substital but they're harder to use and more limited in things like the range you can change the subtitle timing

**Comment by pohuing** [comment]
After hacking around for an afternoon I got asbplayer to "work" on Firefox. Though I'm not sure which features are broken still, I only started using it today 😅. I've only tested the subs so far, no clue what else is still broken.
Currently [my fork ](https://github.com/pohuing/asbplayer/commit/0daedf8b78c0f3707af838ed69871adcdec30fc7)requires a prerelease version of Firefox 115 to work[(in my case 117.0a1)](https://www.mozilla.org/en-US/firefox/117.0a1/releasenotes/), because of the [chrome.storage.session ](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/session)api which is still in preview in firefox.
That aside my changes are mostly removing chrome specific apis with firefox replacements if possible. 

I'm not a webdev nor an extension dev, so I can't judge how feasible this is to support on multiple browsers at once. I'm generally surprised by how well it works, considering I only changed a couple lines.

**Comment by pedipanol** [comment]
@pohuing can you provide a build? I tried building myself but yarn keeps giving out errors

**Comment by pohuing** [comment]
@pedipanol to be honest, it just stopped working over night and I don't have a clue why. That most recent commit worked at one point, now it doesn't and I don't need this extension enough to continue sinking time into it. 

Maybe there's a better way to debug this, but I can't get a source map to work and staring at compiled async state machines is just horrid to debug.

Providing a build also isn't an easy thing unfortunately. Firefox wants to become the new apple and requires you to install non Firefox approved(tm) extensions on every launch. I'd have to jump through signing hoops with them for me to be able to share a usable build.

What is the error yarn is showing you?

**Comment by jp-man25** [comment]
Completely switched to Firefox only to find out asbplayer isn't compatible :(
I only really use it to add subs and be able to scan them, so I don't really care if the sentence audio or image stuff doesn't work.

**Comment by killergerbah** [comment]
A snapshot build with Firefox support has been posted in the Discord server. It is missing the side panel and the ability to record DRM-protected video streams.
